### ISSUE TITLE
Add gh-action for updating dropdown menus

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/mbon-docs#30]
xref:
* https://github.com/ioos/documentation-theme-jekyll/issues/2
* https://github.com/ioos/ioos-documentation-jekyll-skeleton/issues/4

```yaml
steps:
- name: Checkout repository
  uses: actions/checkout@v2
- name: Checkout submodules
  run: git submodule update --init --recursive
```

gh-action cron https://docs.getnacelle.com/deployment/scheduled-builds-github-actions.html#configure-the-schedule
